export {default as About} from "./About" 
export {default as Disclaimer} from "./Disclaimer" 
export {default as Help} from "./Help" 
export {default as Privacy} from "./Privacy" 
export {default as Terms} from "./Terms" 
export {default as TextFileDesign} from "./TextFileDesign" 